version: '3.3'
services:
  build-container: 
    image: avertem/avertem-dev:latest
    user: "${UID}:${GID}"
    volumes:
      - ../../src/:/opt/avertem/src/
      - ../../scripts/:/opt/avertem/scripts/
      - ../../builds:/opt/avertem/builds/
      - ../../builds/scripts/build_in_docker.sh:/opt/avertem/build.sh
      - ../../Doxyfile:/opt/avertem/Doxyfile
      - ../../CMakeLists.txt:/opt/avertem/CMakeLists.txt
      - ../../deps_build/:/opt/avertem/deps_build/
      - ../../build/:/opt/avertem/build/
      - ../../ide_build/:/opt/avertem/ide_build/
      - ../../LICENSE.md:/opt/avertem/LICENSE.md
      - ../../deps_build/CMakeLists.txt:/opt/avertem/deps_build/CMakeLists.txt
      - ../../documents/:/opt/avertem/documents/
      - ../../resources/:/opt/avertem/resources/
      - ../../keys/:/opt/avertem/keys/
      - ../../contracts/:/opt/avertem/contracts/
      - ../../avertem.doxygen.in:/opt/avertem/avertem.doxygen.in
      - ../../dependencies/:/opt/dependencies/
    environment:
      - HOME=/

